
# This file is automatically generated, you probably don't want to edit this

ttestPSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestPSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pairs = NULL,
            alternative = "two.sided",
            testType = "parametric",
            confLevel = 0.95,
            normalityTest = FALSE, ...) {

            super$initialize(
                package="tTestLFHK",
                name="ttestPS",
                requiresData=TRUE,
                ...)

            private$..pairs <- jmvcore::OptionPairs$new(
                "pairs",
                pairs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "two.sided",
                    "less",
                    "greater"),
                default="two.sided")
            private$..testType <- jmvcore::OptionList$new(
                "testType",
                testType,
                options=list(
                    "parametric",
                    "nonparametric"),
                default="parametric")
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=0.95,
                min=0,
                max=1)
            private$..normalityTest <- jmvcore::OptionBool$new(
                "normalityTest",
                normalityTest,
                default=FALSE)

            self$.addOption(private$..pairs)
            self$.addOption(private$..alternative)
            self$.addOption(private$..testType)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..normalityTest)
        }),
    active = list(
        pairs = function() private$..pairs$value,
        alternative = function() private$..alternative$value,
        testType = function() private$..testType$value,
        confLevel = function() private$..confLevel$value,
        normalityTest = function() private$..normalityTest$value),
    private = list(
        ..pairs = NA,
        ..alternative = NA,
        ..testType = NA,
        ..confLevel = NA,
        ..normalityTest = NA)
)

ttestPSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestPSResults",
    inherit = jmvcore::Group,
    active = list(
        ttestParPS = function() private$.items[["ttestParPS"]],
        ttestNonparPS = function() private$.items[["ttestNonparPS"]],
        normalityPS = function() private$.items[["normalityPS"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Paired Samples T Test/Wilcoxon Signed Rank Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="ttestParPS",
                title="Paired Samples Test",
                rows="(pairs)",
                columns=list(
                    list(
                        `name`="x", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="y", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="testName", 
                        `title`="Test type", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="crit", 
                        `title`="Critical value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="mean", 
                        `title`="Mean Difference", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ttestNonparPS",
                title="Paired Samples Test",
                rows="(pairs)",
                columns=list(
                    list(
                        `name`="x", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="y", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="testName", 
                        `title`="Test type", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="normalityPS",
                title="Normality test (Shapiro-Wilk) for differences",
                rows="(pairs)",
                columns=list(
                    list(
                        `name`="x", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="y", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="w", 
                        `title`="W", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

ttestPSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestPSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tTestLFHK",
                name = "ttestPS",
                version = c(1,1,0),
                options = options,
                results = ttestPSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Paired Samples T-Test/Wilcoxon Signed Rank Test
#'
#' 
#' @param data the data as a data frame
#' @param pairs pairs of variable in `data' representing the paired
#'   measurements; in R, a list of lists
#' @param alternative \code{'Mean of differences of the two measurements is
#'   not 0'}, \code{'Mean of Measurement 1 minus Measurement 2 is less than 0'},
#'   or \code{'Mean of Measurement 1 minus Measurement 2 is greater than 0'}
#' @param testType \code{'Parametric'} uses Student's t-test,
#'   \code{'Nonparametric'} uses Mann-Whitney U test.
#' @param confLevel a number between 0 and 1 (default: 0.95), specifying the
#'   confidence interval width
#' @param normalityTest whether to perform a test for normality of the
#'   distribution of the differences
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ttestParPS} \tab \tab \tab \tab \tab the main result table for the parametric case \cr
#'   \code{results$ttestNonparPS} \tab \tab \tab \tab \tab the main result table for the nonparametric case \cr
#'   \code{results$normalityPS} \tab \tab \tab \tab \tab the results of the normality test for the differences \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttestParPS$asDF}
#'
#' \code{as.data.frame(results$ttestParPS)}
#'
#' @export
ttestPS <- function(
    data,
    pairs,
    alternative = "two.sided",
    testType = "parametric",
    confLevel = 0.95,
    normalityTest = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ttestPS requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- ttestPSOptions$new(
        pairs = pairs,
        alternative = alternative,
        testType = testType,
        confLevel = confLevel,
        normalityTest = normalityTest)

    analysis <- ttestPSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

