
# This file is automatically generated, you probably don't want to edit this

ttestISOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestISOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            group = NULL,
            alternative = "two.sided",
            testType = "parametric",
            confLevel = 0.95,
            normalityTest = FALSE, ...) {

            super$initialize(
                package="tTestLFHK",
                name="ttestIS",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "two.sided",
                    "less",
                    "greater"),
                default="two.sided")
            private$..testType <- jmvcore::OptionList$new(
                "testType",
                testType,
                options=list(
                    "parametric",
                    "nonparametric"),
                default="parametric")
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=0.95,
                min=0,
                max=1)
            private$..normalityTest <- jmvcore::OptionBool$new(
                "normalityTest",
                normalityTest,
                default=FALSE)

            self$.addOption(private$..deps)
            self$.addOption(private$..group)
            self$.addOption(private$..alternative)
            self$.addOption(private$..testType)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..normalityTest)
        }),
    active = list(
        deps = function() private$..deps$value,
        group = function() private$..group$value,
        alternative = function() private$..alternative$value,
        testType = function() private$..testType$value,
        confLevel = function() private$..confLevel$value,
        normalityTest = function() private$..normalityTest$value),
    private = list(
        ..deps = NA,
        ..group = NA,
        ..alternative = NA,
        ..testType = NA,
        ..confLevel = NA,
        ..normalityTest = NA)
)

ttestISResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestISResults",
    inherit = jmvcore::Group,
    active = list(
        ttestParIS = function() private$.items[["ttestParIS"]],
        ttestNonparIS = function() private$.items[["ttestNonparIS"]],
        homogeneityIS = function() private$.items[["homogeneityIS"]],
        normalityIS = function() private$.items[["normalityIS"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Independent Samples T-Test/Mann-Whitney U Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="ttestParIS",
                title="Independent Samples Test",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE, 
                        `content`="($key)"),
                    list(
                        `name`="testName", 
                        `title`="Test type", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="crit", 
                        `title`="Critical value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="mean1", 
                        `title`="Mean 1", 
                        `combineBelow`=TRUE, 
                        `type`="number"),
                    list(
                        `name`="mean2", 
                        `title`="Mean 2", 
                        `combineBelow`=TRUE, 
                        `type`="number"),
                    list(
                        `name`="meandiff", 
                        `title`="Difference in means", 
                        `combineBelow`=TRUE, 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ttestNonparIS",
                title="Independent Samples Test",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE, 
                        `content`="($key)"),
                    list(
                        `name`="testName", 
                        `title`="Test type", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="homogeneityIS",
                title="Homogeneity of Variances Test (Levene)",
                rows="(deps)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE, 
                        `content`="($key)"),
                    list(
                        `name`="f", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="df2", 
                        `title`="df2", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="normalityIS",
                title="Normality test (Shapiro-Wilk)",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="group", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="w", 
                        `title`="W", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

ttestISBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestISBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tTestLFHK",
                name = "ttestIS",
                version = c(1,1,0),
                options = options,
                results = ttestISResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Independent Samples T-Test/Mann-Whitney U Test
#'
#' 
#' @param data the data as a data frame
#' @param deps a list of strings each specifying a dependent variable in
#'   \code{data}
#' @param group a string specifying the grouping variable in \code{data}; must
#'   have exactly two levels
#' @param alternative \code{'Difference of means of the groups is different'},
#'   \code{'Mean of Group 1 is less than mean of Group 2'}, or \code{'Mean of
#'   Group 1 is greater than mean of Group 2'}
#' @param testType \code{'Parametric'} uses Student's t-test and Welch's
#'   t-test, \code{'Nonparametric'} uses Mann-Whitney U test.
#' @param confLevel a number between 0 and 1 (default: 0.95), specifying the
#'   confidence interval width
#' @param normalityTest whether to perform tests for normality of the two
#'   distributions
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ttestParIS} \tab \tab \tab \tab \tab the main result table for the parametric case \cr
#'   \code{results$ttestNonparIS} \tab \tab \tab \tab \tab the main result table for the nonparametric case \cr
#'   \code{results$homogeneityIS} \tab \tab \tab \tab \tab the Levene results, only used in the parametric case \cr
#'   \code{results$normalityIS} \tab \tab \tab \tab \tab the results of the normality test for the difference \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttestParIS$asDF}
#'
#' \code{as.data.frame(results$ttestParIS)}
#'
#' @export
ttestIS <- function(
    data,
    deps,
    group,
    alternative = "two.sided",
    testType = "parametric",
    confLevel = 0.95,
    normalityTest = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ttestIS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ttestISOptions$new(
        deps = deps,
        group = group,
        alternative = alternative,
        testType = testType,
        confLevel = confLevel,
        normalityTest = normalityTest)

    analysis <- ttestISClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

