
# This file is automatically generated, you probably don't want to edit this

ttestOSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestOSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            xs = NULL,
            alternative = "two.sided",
            mean = 0,
            testType = "parametric",
            confLevel = 0.95,
            normalityTest = FALSE, ...) {

            super$initialize(
                package="tTestLFHK",
                name="ttestOS",
                requiresData=TRUE,
                ...)

            private$..xs <- jmvcore::OptionVariables$new(
                "xs",
                xs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "two.sided",
                    "less",
                    "greater"),
                default="two.sided")
            private$..mean <- jmvcore::OptionNumber$new(
                "mean",
                mean,
                default=0)
            private$..testType <- jmvcore::OptionList$new(
                "testType",
                testType,
                options=list(
                    "parametric",
                    "nonparametric"),
                default="parametric")
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=0.95,
                min=0,
                max=1)
            private$..normalityTest <- jmvcore::OptionBool$new(
                "normalityTest",
                normalityTest,
                default=FALSE)

            self$.addOption(private$..xs)
            self$.addOption(private$..alternative)
            self$.addOption(private$..mean)
            self$.addOption(private$..testType)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..normalityTest)
        }),
    active = list(
        xs = function() private$..xs$value,
        alternative = function() private$..alternative$value,
        mean = function() private$..mean$value,
        testType = function() private$..testType$value,
        confLevel = function() private$..confLevel$value,
        normalityTest = function() private$..normalityTest$value),
    private = list(
        ..xs = NA,
        ..alternative = NA,
        ..mean = NA,
        ..testType = NA,
        ..confLevel = NA,
        ..normalityTest = NA)
)

ttestOSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestOSResults",
    inherit = jmvcore::Group,
    active = list(
        ttestParOS = function() private$.items[["ttestParOS"]],
        ttestNonparOS = function() private$.items[["ttestNonparOS"]],
        normalityOS = function() private$.items[["normalityOS"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One Sample T-Test/One Sample Wilcoxon Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="ttestParOS",
                title="One Sample Test",
                rows="(xs)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="testName", 
                        `title`="Test type", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="crit", 
                        `title`="Critical value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ttestNonparOS",
                title="One Sample Test",
                rows="(xs)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="testName", 
                        `title`="Test type", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="normalityOS",
                title="Normality test (Shapiro-Wilk)",
                rows="(xs)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="w", 
                        `title`="W", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

ttestOSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestOSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tTestLFHK",
                name = "ttestOS",
                version = c(1,1,0),
                options = options,
                results = ttestOSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' One Sample T-Test/One Sample Wilcoxon Test
#'
#' 
#' @param data the data as a data frame
#' @param xs a list of strings each specifying a variable in \code{data}
#' @param alternative \code{'Mean not equal to test value'}, \code{'Mean less
#'   than test value'}, or \code{'Mean greater than test value'}
#' @param mean The true value of the mean
#' @param testType \code{'Parametric'} uses Student's t-test,
#'   \code{'Nonparametric'} uses Wilcoxon rank test.
#' @param confLevel a number between 0 and 1 (default: 0.95), specifying the
#'   confidence interval width
#' @param normalityTest whether to perform a test for normality of the
#'   distribution
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ttestParOS} \tab \tab \tab \tab \tab the main result table for the parametric case \cr
#'   \code{results$ttestNonparOS} \tab \tab \tab \tab \tab the main result table for the nonparametric case \cr
#'   \code{results$normalityOS} \tab \tab \tab \tab \tab the results of the normality test \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttestParOS$asDF}
#'
#' \code{as.data.frame(results$ttestParOS)}
#'
#' @export
ttestOS <- function(
    data,
    xs,
    alternative = "two.sided",
    mean = 0,
    testType = "parametric",
    confLevel = 0.95,
    normalityTest = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ttestOS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(xs)) xs <- jmvcore::resolveQuo(jmvcore::enquo(xs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(xs), xs, NULL))


    options <- ttestOSOptions$new(
        xs = xs,
        alternative = alternative,
        mean = mean,
        testType = testType,
        confLevel = confLevel,
        normalityTest = normalityTest)

    analysis <- ttestOSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

